import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DarkModeToggle from "./components/DarkModeToggle";
import { FaGithub , FaLinkedin , FaInstagram  } from "react-icons/fa";
import { FaSquareXTwitter } from "react-icons/fa6";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar bg-base-100 dark:bg-midnight-950 dark:text-white drop-shadow-2xl  fixed  z-50" >
        <div className="navbar-start">
          <div className="dropdown">
            <div tabIndex={0} role="button" className="btn btn-ghost lg:hidden">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h8m-8 6h16" />
            </svg>
            </div>
            <ul tabIndex={0} className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow dark:bg-slate-800 dark:text-white rounded-box w-52">
              <li><a className="hover:text-aquamarine-500">About</a></li>
              <li><a className="hover:text-aquamarine-500">Experience</a></li>
              <li><a className="hover:text-aquamarine-500">Projects</a></li>
              <li><a className="hover:text-aquamarine-500">Blog</a></li>
            </ul>
          </div>
          <a className="btn btn-ghost text-3xl text-aquamarine-500  drop-shadow-[2px_5px_5px_rgba(20, 237, 211, 1)] ">M/I</a>
        </div>
        <div className="navbar-center hidden lg:flex ">
          <ul className="menu menu-horizontal px-1  dark:text-white">
              <li><a className="hover:text-aquamarine-500">About</a></li>
              <li><a className="hover:text-aquamarine-500">Experience</a></li>
              <li><a className="hover:text-aquamarine-500">Projects</a></li>
              <li><a className="hover:text-aquamarine-500">Blog</a></li>
          </ul>
        </div>
        <div className="navbar-end">
        <DarkModeToggle />
        </div>
      </div> 



      <ol className="fixed z-50 bottom-20 left-10 overflow-hidden space-y-8 lg:block hidden">
      <li className="relative flex-1 after:content-['']  after:w-0.5 after:h-full   after:inline-block after:absolute after:-bottom-12 after:left-4 lg:after:left-5">
          <a className="flex items-center font-medium w-full  ">
              <span className="w-8 h-8 rounded-full flex justify-center items-center mr-3 text-sm  lg:w-8 lg:h-8"><FaGithub className="hover:fill-aquamarine-500 dark:hover:fill-aquamarine-500 dark:fill-slate-500 lg:w-8 lg:h-8 " /></span>
          </a>
      </li>
      <li className="relative flex-1 after:content-['']  after:w-0.5 after:h-full   after:inline-block after:absolute after:-bottom-12 after:left-4 lg:after:left-5">
          <a className="flex items-center font-medium w-full  ">
              <span className="w-8 h-8 rounded-full flex justify-center items-center mr-3 text-sm  lg:w-8 lg:h-8"><FaLinkedin className="hover:fill-aquamarine-500 dark:hover:fill-aquamarine-500 dark:fill-slate-500 lg:w-8 lg:h-8 "/></span>
          </a>
      </li>
      <li className="relative flex-1 ">
          <a className="flex items-center font-medium w-full  ">
              <span className="w-8 h-8  rounded-full flex justify-center items-center mr-3 text-sm  lg:w-8 lg:h-8"><FaInstagram className="hover:fill-aquamarine-500 dark:hover:fill-aquamarine-500 dark:fill-slate-500 lg:w-8 lg:h-8 "/></span>
          </a>
      </li>
      <li className="relative flex-1 ">
          <a className="flex items-center font-medium w-full  ">
              <span className="w-8 h-8 rounded-full flex justify-center items-center mr-3 text-sm  lg:w-8 lg:h-8"><FaSquareXTwitter className="hover:fill-aquamarine-500 dark:hover:fill-aquamarine-500 dark:fill-slate-500 lg:w-8 lg:h-8 "/></span>
          </a>
      </li>
      </ol>


        {children}
      </body>
    </html>
  );
}
